client.focused          #6f24cf #6f24cf #ffffff #6f24cf #6f24cf
client.focused_inactive #d1cdd8 #eceaf2 #17151b #d1cdd8 #d1cdd8
client.unfocused        #ebe8ef #f4f3f8 #625e69 #ebe8ef #ebe8ef
client.urgent           #ba1a1a #ba1a1a #ffffff #ba1a1a #ba1a1a
